import { useEffect } from 'react'
import * as wasm from "crate" 

export default function App() {
  useEffect(() => {
    const startWasm = async () => {
      try {
        // ESLintの指摘通り @ts-expect-error を使い、
        // かつ Wasmの初期化関数を確実に呼び出す
        // @ts-expect-error: wasm.default is generated by wasm-pack
        await wasm.default(); 

        // TSエラー「0個の引数が必要」への対応：
        // Rust側のデフォルトのgreetは引数なしか、あるいは引数が違う可能性があるため
        // 一旦引数なしで呼ぶか、型を無視して実行する
        // @ts-expect-error: greet might have different signature in generated types
        wasm.greet("WebAssembly");
        
      } catch (err) {
        console.error("Wasm initiation failed:", err);
      }
    };
    
    startWasm();
  }, []);

  return (
    <div style={{ padding: "20px", textAlign: "center" }}>
      <h1>Rust + Wasm + React GA Project</h1>
      <p>ブラウザのアラートが表示されたら疎通成功です！</p>
    </div>
  )
}